### ISSUE TITLE
Read ROS_DISTRO command line variable in ros2snap

### ISSUE THREAD

**Issue by jackieokay** [erlerobot/ros2snap#3]
Currently `ros2snap` has a hardcoded value for the distribution, `indigo`, which will not work on machines with different distributions installed. The script should read `$ROS_DISTRO` from the environment, and perhaps offer a `-d` option to specify another distribution if `$ROS_DISTRO` is not set.

**Comment by vmayoral** [comment]
Thanks @jacquelinekay, I like the idea of a `-d` option. I can see it implemented it already [here](https://github.com/jacquelinekay/ros2snap/blob/documentation_deps/ros2snap#L59). Closing.
